### ISSUE TITLE
TypeScript error when importing SVG - Module '"*.svg"' has no exported member 'ReactComponent'

### ISSUE THREAD

**Issue by craig-o-curtis** [pd4d10/vite-plugin-svgr#3]
I'm getting an error about TS not recognizing the type at `import { ReactComponent as HelloSvg } from "../assets/hello.svg";`

<img width="792" alt="image" src="https://user-images.githubusercontent.com/12050799/108758475-5fa88580-7508-11eb-8589-909d1d16cc22.png">

Vite says there is SVG support.
`client.d.ts` lines 128-131 has the following:

```
declare module '*.svg' {
  const src: string
  export default src
}
```

**Comment by gunters63** [comment]
I had the same problem.
I found a workaround by putting this code into `index.d.ts` in my source root dir:

````
// Fix typescript error for plugin vite-plugin-svgr

declare module '*.svg' {
  import * as React from 'react';

  export const ReactComponent: React.FunctionComponent<
    React.SVGProps<SVGSVGElement> & { title?: string }
  >;

  const src: string;
  export default src;
}
````

The type definitions where shamelessly stolen from the react type definitions here: [react-app.d.ts](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/lib/react-app.d.ts) :)

I am pretty sure this type definition could also be added to the plugin itself.

**Comment by EndlessHollow** [comment]
Hello @pd4d10,

I was looking into providing the module typing proposed by gunters63. I checked how vite has done it and it has it as `client.d.ts` in root and in `package.json` as `"files": ["client.d.ts"]`. I tried it via yarn link. A user would need to provide into the `.tsconfig` something like `"types": ["vite-plugin-svgr/client"]` and that should do the trick. I am just wondering if vite is somehow generating the client.d.ts since I could not find it and `d.ts` files are generated from `.ts` files, correct me if I am wrong.

Best Regards!

**Comment by ttqftech** [comment]
For whom using **pnpm** and still get this problem after setting `"types": ["vite-plugin-svgr/client"]`, try this line instead.
```
"types": [".pnpm/registry.npmmirror.com+vite-plugin-svgr@2.2.1_vite@3.1.6/node_modules/vite-plugin-svgr/client"],
```
(Change the path to your real path)
Not sure if anyone has the same experience.
