### ISSUE TITLE
TS error

### ISSUE THREAD

**Issue by JS-mark** [pd4d10/vite-plugin-svgr#9]
![image](https://user-images.githubusercontent.com/31335385/126268969-d2d126f5-979a-433b-807a-3e7142afc042.png)

**Comment by lucsky** [comment]
Looks like the module declaration in [client.d.ts](https://github.com/pd4d10/vite-plugin-svgr/blob/83b07cb59a996e4e2b3ba29990e0db0f9c6c4fc6/client.d.ts#L3) conflicts with the default one from Vite [here](https://github.com/vitejs/vite/blob/828a8e538ce289922b9301339be4d5d6ea84b496/packages/vite/client.d.ts#L86).

A simple fix would be to add a special loader query, like so:

```declare module '*.svg?component' { ... }```

But this would then force users of this plugin to write

```import { ReactComponent as Foo } from 'path/to/foo.svg?component'```
instead of
```import { ReactComponent as Foo } from 'path/to/foo.svg'```

Right?

**Comment by lucsky** [comment]
Come to think of it, this might also be a good occasion to switch the default export to the component rather than the src, so instead of

```import { ReactComponent as Foo } from 'path/to/foo.svg?component'```

one could do

```import Foo from 'path/to/foo.svg?component'```

to get the React component, and doing

```import Foo from 'path/to/foo.svg'```

would "fallback" to the default Vite behavior which return the source, which I think makes sense.

But all these would definitely be breaking changes. But that might be fine for 0.x release, I guess ?

**Comment by pd4d10** [comment]
Looks like removing `export default src` would solve this issue?

**Comment by JS-mark** [comment]
> Looks like removing `export default src` would solve this issue?

Yes, I can re-assign the value and it can be used! But it looks like the author of the library needs to modify it!

**Comment by pd4d10** [comment]
Should be fixed in the latest v0.4.0, by https://github.com/pd4d10/vite-plugin-svgr/pull/12
